### ISSUE TITLE
Adjust CSS of postcards template

### ISSUE THREAD

**Issue by larnsce** [seankross/postcards#40]
### What I am doing 

I am using the poctcards::jolla template as the index.Rmd for a website using the [distill framework](https://rstudio.github.io/distill/website.html#postcards). 

### What I want to do

I want to edit the CSS style of the index.html to

- ~Show a square image instead of using "class: rounded-circle"~
- Remove the navbar for this page only

### What I have tried

I have created a custom CSS using `distill::create_theme(name = "theme")` and then tried to use the `theme.css` file in the YAML header of the index.Rmd. Without success.

### Questions

1. ~How do I get a square image, so that it doesn't get cut off on the edges?~
2. How can I remove the navbar from index.html?

### My YAML of the index.Rmd:

```
---
title: ""
image: "img/Azores_logo_UiV.png"
theme: theme.css 
links:
  - label: Blog
    url: blog.html
  - label: About
    url: about.html
output:
  postcards::jolla
site: distill::distill_website
---
```

### The result as a screenshot:

![Screenshot 2021-04-09 at 10 18 58](https://user-images.githubusercontent.com/18212549/114151976-fea10980-991d-11eb-80d3-d845d4330285.png)
