### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by drfurtado** [seankross/postcards#56]
How do I use different icons under the profile picture; for instance, rounded icons?

**Comment by pederengelstad** [comment]
Here's an example of how I set mine up in the YAML. You can customize your own icon choices.

```
links:
  - label: '<i class="ai ai-google-scholar-square ai-3x" style="color:#4387f6"></i>'
    url: "https://scholar.google.com/citations?user=kR_0IvYAAAAJ&hl=en"
  - label: '<i class="ai ai-researchgate-square ai-3x" style="color:#00a39e"></i>'
    url: "https://www.researchgate.net/profile/Peder-Engelstad"
  - label: '<i class="fa fa-github fa-3x" style="color:#4B0082;"></i>'
    url: "https://github.com/pederengelstad"
  - label: '<i class="fa-brands fa-linkedin fa-3x" style="color:#0c64c4"></i>'
    url: "https://www.linkedin.com/in/peder-engelstad/"
  - label: '<i class="fa-brands fa-mastodon fa-3x" style="color:#595aff"></i>'
    url: "https://ecoevo.social/\\@pederengelstad"
  - label: '<i class="fa-regular fa-envelope fa-3x"></i>'
    url: "mailto:peder.engelstad@colostate.edu"
output:
  postcards::trestles
editor_options: 
  markdown: 
    wrap: 72
```
